language: python

python:
    - "2.7"

install:
    pip install tox

env:
    - TOXENV = py27-django18
    - TOXENV = py27-django19
    - TOXENV = py3-django18
    - TOXENV = py3-django19

script:
    tox

branches:
    only:
        - master
        - dev